blog/urls.py
# -*- coding: utf-8 -*-
"""bourseLibre URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add an import:  from blog__ import urls as blog_urls
    2. Add a URL to urlpatterns:  url(r'^blog__/', include(blog_urls))
"""
from django.conf.urls import url
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'blog'

urlpatterns = [
    url(r'^accueil/$', views.accueil, name="forum"),
    url(r'^articles/$', views.ListeArticles.as_view(), name="index"),
    # url(r'^newPost/', views.ajouterArticle, name='ajouterArticle'),
    # url(r'^article/(?P<slug>.+)$', views.lire, name='lire'),

    url(r'^article/(?P<slug>[-\w]+)$', views.lireArticle, name='lireArticle'),
    url(r'^modifierArticle/(?P<slug>[-\w]+)$', login_required(views.ModifierArticle.as_view(), login_url='/auth/login/'), name='modifierArticle'),
    url(r'^suiveursArticle/(?P<slug>[-\w]+)$', views.articles_suivis, name='suiveursArticle'),
    url(r'^supprimerArticle/(?P<slug>[-\w]+)$', login_required(views.SupprimerArticle.as_view(), login_url='/auth/login/'), name='supprimerArticle'),
    url(r'^ajouterArticle/$', login_required(views.ajouterArticle), name='ajouterNouvelArticle'),

    url(r'^suivre_article/(?P<slug>[-\w]+)/$', views.suivre_article, name='suivre_article'),
    url(r'^suivre_articles/$', views.suivre_articles, name='suivre_articles'),

    url(r'^modifierCommentaireArticle/(?P<id>[0-9]+)$',
        login_required(views.ModifierCommentaireArticle.as_view(), login_url='/auth/login/'),
        name='modifierCommentaireArticle'),
    url(r'ajouterEvenement/$', views.ajouterEvenement, name='ajouterEvenement'),
    url(r'ajouterEvenementArticle/(?P<id>[0-9]+)$', views.ajouterEvenementArticle, name='ajouterEvenementArticle'),

]

cal/urls.py
# cal/urls.py

from django.conf.urls import url
from . import views

app_name = 'cal'
urlpatterns = [
    url(r'', views.agenda, name='agenda'),
]

uppm/urls.py
from django.urls import path
from django.conf.urls import include, url
from uppm import views
from django.views.generic import TemplateView
from .views import handler400 as h400, handler403  as h403, handler404  as h404, handler500  as h500

# On import les vues de Django, avec un nom spécifique
from django.contrib.auth.decorators import login_required

# admin.autodiscover()
from django.contrib import admin

urlpatterns = [
    url(r'^summernote/', include('django_summernote.urls')),
    url(r'^captcha/', include('captcha.urls')),
    path(r'agenda/', include('cal.urls')),
    url(r'^forum/', include('blog.urls', namespace='bourseLibre.blog')),
    url('^', include('django.contrib.auth.urls')),
    url(r'^$', views.bienvenue, name='bienvenue'),
    url(r'^bienvenue/$', views.bienvenue, name='bienvenue'),
    url(r'^faq/$', views.faq, name='faq'),
    url(r'^gallerie/$', views.gallerie, name='gallerie'),
    url(r'^notifications/$', views.notifications, name='notifications'),
    url(r'^notifications/news/$', views.notifications_news, name='notifications_news'),
    url(r'^notificationsParDate/$', views.notificationsParDate, name='notificationsParDate'),
    url(r'^notificationsLues/$', views.notificationsLues, name='notificationsLues'),
    url(r'^dernieresInfos/$', views.dernieresInfos, name='dernieresInfos'),
    url(r'^site/presentation/$', views.presentation_site, name='presentation_site'),
    url(r'^gestion/', admin.site.urls, name='admin',),
    url(r'^merci/$', views.merci, name='merci'),
    url(r'^chercher/produit/$', login_required(views.chercher), name='chercher'),
    url(r'^accounts/profil/(?P<user_id>[0-9]+)/$', login_required(views.profil), name='profil', ),
    url(r'^accounts/profil/(?P<user_username>[-\w.]+)/$', login_required(views.profil_nom), name='profil_nom', ),
    url(r'^accounts/profile/$', login_required(views.profil_courant), name='profil_courant', ),
    url(r'^accounts/profil_inconnu/$', views.profil_inconnu, name='profil_inconnu', ),
    url(r'^accounts/profil_modifier/$', login_required(views.profil_modifier.as_view()), name='profil_modifier', ),
    url(r'^accounts/profil_supprimer/$', login_required(views.profil_supprimer.as_view()), name='profil_supprimer', ),
    url(r'^accounts/profil_contact/(?P<user_id>[0-9]+)/$', login_required(views.profil_contact), name='profil_contact', ),
    url(r'^register/$', views.register, name='senregistrer', ),
    url(r'^password/change/$', views.change_password, name='change_password'),
    path('auth/', include('django.contrib.auth.urls')),

    url(r'^contact_admins/$', views.contact_admins, name='contact_admins', ),
    url(r'^cgu/$', views.cgu, name='cgu', ),
    url(r'^liens/$', views.liens, name='liens', ),
    url(r'^fairedon/$', views.fairedon, name='fairedon', ),
    #url(r'^agenda/$', views.agenda, name='agenda',),
    url(r'^cooperateurs/annuaire/$', login_required(views.annuaire), name='annuaire', ),
    url(r'^cooperateurs/listeFollowers/$', login_required(views.listeFollowers), name='listeFollowers', ),
    url(r'^cooperateurs/carte/$', login_required(views.carte), name='carte', ),

    url(r'^conversations/(?P<destinataire>[-\w.]+)$', login_required(views.lireConversation), name='agora_conversation'),
    url(r'^conversations/(?P<destinataire1>[-\w.]+)/(?P<destinataire2>[-\w.]+)$', login_required(
        views.lireConversation_2noms), name='lireConversation_2noms'),
    url(r'^conversations/$', login_required(views.ListeConversations.as_view()), name='conversations'),
    url(r'^conversations/chercher/$', login_required(views.chercherConversation), name='chercher_conversation'),
    url(r'^suivre_conversation/$', views.suivre_conversations, name='suivre_conversations'),
    url(r'^agora/$', login_required(views.agora), name='agora_general'),
    url(r'^activity/', include('actstream.urls')),
    url(r'^inscription_newsletter/$', views.inscription_newsletter, name='inscription_newsletter', ),
    url(r'^modifierMessage/(?P<id>[0-9]+)(?P<type>[-\w.]+)$', views.modifier_message, name='modifierMessage'),
]


urlpatterns += [
    url(r'^robots\.txt$', TemplateView.as_view(template_name="uppm/robots.txt", content_type='text/plain')),
]

from django.conf import settings
if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = h404
handler500 = h500
handler400 = h400
handler403 = h403

if settings.LOCALL:
    import debug_toolbar
    urlpatterns = [url(r'^__debug__/', include(debug_toolbar.urls)),] + urlpatterns
    #urlpatterns += url('',(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}))

blog/models.py
from django.db import models
from uppm.models import Profil, Suivis
from django.urls import reverse
from django.utils import timezone
from django.core.mail import send_mass_mail
#from tinymce.models import HTMLField
from django.dispatch import receiver
from django.db.models.signals import post_save

from actstream.models import followers

class Choix():
    type_annonce = ('0','Atelier philo'), ('1','Boite à idée'), \
                   ('2', 'Intendance, logistique'), ('3', 'Projets futurs'), \
                   ('4',"Conférence mensuelle"),
    couleurs_annonces = {
       # 'Annonce':"#e0f7de", 'Administratif':"#dcc0de", 'Agenda':"#d4d1de", 'Entraide':"#cebacf",
       # 'Chantier':"#d1ecdc",'Jardinage':"#fcf6bd", 'Recette':"#d0f4de", 'Bricolage':"#fff2a0",
       # 'Culture':"#ffc4c8", 'Bon_plan':"#bccacf", 'Point':"#87bfae", 'Autre':"#bcb4b4"

        '0':"#d1ecdc",
        '1':"#D4CF7D",
        '2':"#E0E3AB",
        '3':"#AFE4C1",
        '4':"#fff2a0",
        '5':"#B2AFE4",
        '6':"#d0f4de",
        '7':"#b3b6e6",
        '8':"#3EA7BB",
        '9':"#349D9B",
        '10':"#bccacf",
    }

    def get_couleur(categorie):
        try:
            return Choix.couleurs_annonces[categorie]
        except:
            return Choix.couleurs_annonces["6"]

class Article(models.Model):
    categorie = models.CharField(max_length=30,         
        choices=(Choix.type_annonce),
        default='Annonce', verbose_name="categorie")
    titre = models.CharField(max_length=100,)
    auteur = models.ForeignKey(Profil, on_delete=models.CASCADE, default=None)
    slug = models.SlugField(max_length=100)
    contenu = models.TextField(null=True)
    date_creation = models.DateTimeField(verbose_name="Date de parution", default=timezone.now)
    date_modification = models.DateTimeField(verbose_name="Date de modification", default=timezone.now)
    estPublic = models.BooleanField(default=False, verbose_name='Public ou réservé aux membres du collectif ACVI')
    estModifiable = models.BooleanField(default=False, verbose_name="Modifiable par n'importe qui")

    date_dernierMessage = models.DateTimeField(verbose_name="Date du dernier message", auto_now=True)
    dernierMessage = models.CharField(max_length=100, default=None, blank=True, null=True)
    estArchive = models.BooleanField(default=False, verbose_name="Archiver l'article")

    start_time = models.DateTimeField(verbose_name="Date (optionnel, pour affichage dans l'agenda)", null=True,blank=True, help_text="jj/mm/année")
    end_time = models.DateTimeField(verbose_name="Date de fin (optionnel, pour affichage dans l'agenda)",  null=True,blank=True, help_text="jj/mm/année")

    class Meta:
        ordering = ('-date_creation', )
        
    def __str__(self):
        return self.titre

    def get_absolute_url(self):
        return reverse('blog:lireArticle', kwargs={'slug':self.slug})

    def save(self, *args, **kwargs):
        ''' On save, update timestamps '''
        if not self.id:
            self.date_creation = timezone.now()
        return super(Article, self).save(*args, **kwargs)

    @property
    def get_couleur(self):
        if self.categorie in Choix.couleurs_annonces:
            return Choix.couleurs_annonces[self.categorie]
        return Choix.couleurs_annonces["6"]


@receiver(post_save, sender=Article)
def on_save_articles(instance, created, **kwargs):
    if created:
        suivi, created = Suivis.objects.get_or_create(nom_suivi='articles')
        titre = "UPPM - nouvel article"
        message = " Un nouvel article a été créé " + \
                  "\n Vous pouvez y accéder en suivant ce lien : https://uppm66.herokuapp.com" + instance.get_absolute_url() + \
                  "\n\n------------------------------------------------------------------------------" \
                  "\n vous recevez cet email, car vous avez choisi de suivre les articles (en cliquant sur la cloche) sur le site https://uppm66.herokuapp.com/forum/articles/"
        emails = [suiv.email for suiv in followers(suivi) if instance.auteur != suiv and (instance.estPublic or suiv.is_membre_collectif)]
        try:
            send_mass_mail([(titre, message, "siteuppm66@gmail.com", emails), ])
        except:
            pass


class Commentaire(models.Model):
    auteur_comm = models.ForeignKey(Profil, on_delete=models.CASCADE)
    commentaire = models.TextField()
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    date_creation = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.__str__()

    def __str__(self):
        return "(" + str(self.id) + ") "+ str(self.auteur_comm) + ": " + str(self.article)

    @property
    def get_edit_url(self):
        return reverse('blog:modifierCommentaireArticle',  kwargs={'id':self.id})


@receiver(post_save,  sender=Article)
def on_save_article(instance, **kwargs):
    titre = "UPPM - Article actualisé"
    message = "L'article '" +  instance.titre + "' a été modifié (ou quelqu'un l'a commenté)" +\
              "\n Vous pouvez y accéder en suivant ce lien : http://uppm66.herokuapp.com" + instance.get_absolute_url() + \
              "\n\n------------------------------------------------------------------------------" \
              "\n vous recevez cet email, car vous avez choisi de suivre ce projet sur le site https://uppm66.herokuapp.com/forum/articles/"
   # emails = [(titre, message, "asso@perma.cat", (suiv.email, )) for suiv in followers(instance)]
    emails = [suiv.email for suiv in followers(instance)  if instance.auteur != suiv  and (instance.estPublic or suiv.is_membre_collectif)]
    try:
        send_mass_mail([(titre, message, "siteuppm66@gmail.com", emails), ])
    except:
        pass



class Evenement(models.Model):
    titre = models.CharField(verbose_name="Titre de l'événement (si laissé vide, ce sera le titre de l'article)",max_length=100, null=True, blank=True, default="")
    article = models.ForeignKey(Article, on_delete=models.CASCADE, help_text="L'événement doit être associé à un article existant (sinon créez un article avec une date)" )
    start_time = models.DateTimeField(verbose_name="Date", null=False,blank=False, help_text="jj/mm/année" , default=timezone.now)
    end_time = models.DateTimeField(verbose_name="Date de fin (optionnel pour un evenement sur plusieurs jours)",  null=True,blank=True, help_text="jj/mm/année")

    class Meta:
        unique_together = ('article', 'start_time',)

    def get_absolute_url(self):
        return self.article.get_absolute_url()


    @property
    def gettitre(self):
        if not self.titre:
            return self.article.titre
        return self.titre

    @property
    def estPublic(self):
        return self.article.estPublic

blog/templates/blog/accueil.html
{% extends 'blog/baseBlog.html' %}
{% block subtitle %}

<div class="row">
    <div class="col textcenter">
       <h3> Bienvenue sur le forum</h3>
    </div>
</div>

{% endblock %}
{% block content %}

<div class="row">
    <div class="col-sm-12 textcenter">
        <div class="btn-group btn-group-justified">
        <a href="{% url 'agora_general' %}">
         <button type="button" class="btn btn-success">
                 Salon
            </button></a>
         <a href="{% url 'blog:index' %}">
        <button type="button" class="btn btn-success" >
               Articles
            </button>
            </a>
         <a href="{% url 'blog:index_projets' %}">
            <button type="button" class="btn btn-success" >
               Projets
            </button>
            </a>
    </div>
   </div>

{% endblock %}

blog/templates/blog/ajouterEvenement.html
{% extends 'blog/baseBlog.html' %}

{% block subtitle %}
<div class="row justify-content-center">
	<div class="col col-md-12 textcenter"><h3>Ajouter un événement à l'agenda</h3>
		<p>L'événement doit être associé à un article du forum. S'il n'existe pas encore, alors <a href="{% url 'blog:ajouterNouvelArticle' %}" >ajoutez un article</a> et spécifiez-y la date directement</p>
	</div>

	</div>
{% endblock  %}
{% block content %}
{% if error_message %}
<p>
	<strong>{{ error_message }}</strong>
</p>
{% endif %}
<div class="row">
	<div class="col-sm-12">
<form class="form-horizontal" role="form" action="" method="post"
	enctype="multipart/form-data">
	{% csrf_token %} <input type="hidden" name="Evenement" value="{{ article }}"> {% include 'form_template.html'%}
</form>
        <script type="text/javascript">
        {% if not request.user.is_permacat %}
               var isPublic = document.getElementById('id_estPublic').style.visibility = "hidden";
        {%endif%}
    </script>
</div>
    </div>
{% endblock %}

blog/templates/blog/index.html
{% extends 'blog/baseBlog.html' %}
{% load static %}
{% load blog_filters %}
{% load fontawesome %}

{% load activity_tags %}
    {%block header %}
<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'js/infinite.min.js' %}"></script>
    {%endblock%}
{%block subtitle%}

<p>
  <a class="btn {% if request.GET.categorie  %}btn-warning{%else%}btn-primary{%endif%}" style="min-width:180px;" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
    {% if request.GET.categorie  %}
      Articles de la catégorie: {{categorie_courante}}
      {%elif request.GET.permacat %}
      Articles UPPM
      {%elif request.GET.auteur %}
      Articles de {{request.GET.auteur}}
      {%elif typeFiltre == 'archives' %}
      Archives
      {%else%}Catégorie... {%endif%}
  </a>
</p>

<div class="collapse" id="collapseExample">
<div class="row align-items-center">
    <div class="col-sm-12 textcenter justify-content-center ">
        <div class=" justify-content-between">
                            {% for categorie_id, cat_nom, cat_coul in categorie_list %}
            <a class=" btn boutonArticleCategorie " style="background:{{cat_coul}};font-variant: small-caps;{% if request.GET.categorie and cat_nom == categorie_courante %} font-weight: bold;padding:20px 25px;{%endif%}" href="?categorie={{categorie_id}}"><span>{{cat_nom}}</span></a>
                        {% endfor %}
        </div>
    </div>
</div>
    <hr>
    <div class="row align-items-center">
<div class="col-sm-12 textcenter justify-content-center ">
    <nav class="navbar justify-content-center navbar-expand-md navbar-light bg-light">
        <div class="navbar-header">
           <button class=" navbar-toggler btn btn-info btn-block" type="button" data-toggle="collapse" data-target="#navbarProduit" aria-controls="navbarProduitContent" aria-expanded="false" aria-label="Toggle navigation">
               <span class="navbar-toggler-icon"></span>Filtrage...</button>
        </div>
        <div class="collapse navbar-collapse  justify-content-center " id="navbarProduit">
            <ul class="nav navbar-nav justify-content-center ">

                <li class="nav-item dropdown">
        <a href="{% url 'blog:index' %}">
            <button class="btn btn-block {% if typeFiltre == 'aucun' %}btn-primary {%endif%}">Tout </button>
        </a>
   </li>
                <li class="nav-item dropdown">
        <a href="?archives=True">
            <button class="btn btn-block {% if typeFiltre == 'archives' %}btn-primary{%else%}btn-light {%endif%}">Archives </button>
        </a>
            </li>
                <li class="nav-item dropdown">
             <button type="button" class="btn btn-block {% if request.GET.auteur %}btn-primary{%endif%}  dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
               data-target = "#idAuteur">
                {% if request.GET.auteur %} Auteur: {{request.GET.auteur}} {%else%}Auteur{%endif%}
                </button>
            <div class="dropdown-menu"  aria-labelledby="menuAuteur"  id=idAuteur">
                {% for auteur in auteur_list %}
                  <a class="dropdown-item" href="?auteur={{auteur}}">{{auteur}}</a>
                {% endfor %}
            </div>
            </li>


        {% if request.user.is_membre_collectif %}

                <li class="nav-item dropdown">
             <button type="button" class="btn btn-block {% if request.GET.permacat %}btn-primary{%endif%}  dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
               data-target = "#idUPPM">
                {% if request.GET.permacat %}{% if request.GET.permacat == "True" %}UPPM {%else%}Public{%endif%}{%else%}Type{%endif%}
                </button>
            <div class="dropdown-menu"  aria-labelledby="menuStatut"  id=idUPPM">
                  <a class="dropdown-item" href="?permacat=True">UPPM</a>
                  <a class="dropdown-item" href="?permacat=False">Public</a>
            </div>
            </li>
        {%endif%}

                <li class="nav-item dropdown">
                <button class="btn btn-block dropdown-toggle btn-block btn-light" type="button" id="menuOrdreTri" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                   Trier par...
           </button>
                <div class="dropdown-menu"  aria-labelledby="menuOrdreTri"  id="idOrdreTri">
                    {% for ordre in ordreTriPossibles %}
                     <a class="dropdown-item"  href="?{{ request.GET.urlencode }}&ordreTri={{ordre}}">{{ordre|ordreTri}}</a>
                    {% endfor %}
                </div>
            </li>
            </ul>
    </div>
    </nav>
</div>
</div>
</div>

<hr>
<div class="row align-items-center">
<div class="col-sm-12 textcenter">

        <a href="{% url 'blog:ajouterNouvelArticle' %}">
        <button type="button" class="btn  btn-success" >
                <i class="fa fa-plus"></i> Ajouter un article
            </button>
            </a>&ensp;
    &nbsp;
        <a href="{% url 'blog:suivre_articles' %}">

        {% if request.user|is_following:suivis %}
        <button type="button" class="btn btn-light btn-sm" data-toggle="tooltip" data-placement="bottom" title="Cliquez pour arreter de recevoir un mail à chaque nouvel article">
             {% fontawesome_icon 'bell' %} suivi
        </button>
        {% else %}
        <button type="button" class="btn btn-secondary btn-sm" data-toggle="tooltip" data-placement="bottom" title="Cliquez pour recevoir un mail à chaque nouvel article">
             {% fontawesome_icon 'bell-slash' %} non suivi
        </button>
        {% endif %}
            </a>
</div>
</div>
{%endblock%}
{% block content %}

<div class="infinite-container">
    {% for article in article_list %}
    <div class="infinite-item">
            {% include "blog/article_template.html" with article=article %}
    <hr>
    </div>

    {% endfor %}
</div>
{%include 'pagination.html' %}

{% endblock %}

blog/templates/blog/lireArticle.html
{% extends 'blog/baseBlog.html' %}
{% load activity_tags %}
{% load blog_filters %}
{% load fontawesome %}


{% block subtitle %}
{% comment %}

    <div class="row">

        <div class="mobile-toggle">
            <span></span>
            <span></span>
            <span></span>
        </div>

        <nav class="nav2">
            <ul>
                <li><a href="#sec01">Section 01</a></li>
                <li><a href="#sec02">Section 02</a></li>
                <li><a href="#sec03">Section 03</a></li>
                <li><a href=".sec04">Section 04</a></li>
            </ul>
        </nav>

    </div> <!-- / row -->

{% endcomment %}
<div class="row">
    <div class="col-md-2 " id="sec02">
        <p>
        <a  href="{% url 'blog:index'  %}">
        <button class="btn btn-info btn-sm textright" ><i class="fa fa-arrow-left"></i> Sommaire</button>
            </a>
        </p>
    </div>
    <div class="col-md-8">
        <p class="infos  textepetit">Dans: <a href="{% url 'blog:index'  %}?categorie={{article.categorie}}"  style="background-color:{{article.get_couleur}}">{{ article.get_categorie_display }}</a>, rédigé par <a href="{% url 'profil' article.auteur.id %}"> {{ article.auteur.username }}</a>, le {{ article.date_creation|date:"DATE_FORMAT" }};

        <a href="{% url 'blog:suivre_article' article.slug %}">
            {% if request.user|is_following:article %}
            <button type="button" class="btn btn-light btn-sm" data-toggle="tooltip" data-placement="bottom" title=" Cliquez pour arreter de recevoir des notifications concernant cet article par mail">
                 {% fontawesome_icon 'bell' %} Suivi
            </button>
            {% else %}
            <button type="button" class="btn btn-secondary btn-sm" data-toggle="tooltip" data-placement="bottom" title=" Cliquez pour recevoir les notifications concernant cet article par mail">
                 {% fontawesome_icon 'bell-slash' %} Non suivi
            </button>
            {% endif %}
        </a>
            {%comment %}
        <a href="{% url 'blog:suiveursArticle' article.slug %}">
            <button type="button" class="btn btn-secondary btn-sm" data-toggle="tooltip" data-placement="bottom" title=" Cliquez pour recevoir les notifications concernant cet article par mail">
                 {% fontawesome_icon 'eye' %}
            </button>
        </a>
            {% endcomment %}
        </p>
    </div>
    <div class="col-md-2">
        <p>
        {%if article.auteur == request.user %}
		<div class="btn-group">
            <a href="{% url 'blog:modifierArticle' slug=article.slug %}">
               <button type="button" class="btn btn-sm btn-warning">
                <span class="glyphicon glyphicon-plus"></span>&nbsp;Modifier
               </button></a>
            <a href="{% url 'blog:supprimerArticle' slug=article.slug %}">
               <button type="button" class="btn btn-sm btn-danger">
                <span class="glyphicon glyphicon-plus"></span>&nbsp;Supprimer
               </button></a>
        </div>
        {%elif article.estModifiable%}
            <a href="{% url 'blog:modifierArticle' slug=article.slug %}">
               <button type="button" class="btn btn-sm btn-warning">
                <span class="glyphicon glyphicon-plus"></span>&nbsp;Modifier
               </button></a>
        {%endif%}

    </p>
    </div>
</div>


{% endblock %}
{% block content %}
<div class="contenu article ">
<div class="row"  id="sec03">
<div class="col-sm-6 textleft" >

            <span class="badge {% if article.estPublic%}badge-warning{%else%} badge-success {%endif%}">
                Article {%if article.estPublic%} Public {%else%}  Collectif ACVI  {%endif%}
            </span>
            {% if article.estArchive%}
            <span class="badge badge-secondary">
                archivé
            </span>
            {%endif%}
    </div>

    <div class="col-sm-6 textright" >
        {%if article.start_time%}
        <p>
          <a href="{% url 'cal:agenda' %} ">
            {%if article.end_time and article.start_time != article.end_time %}
                Du {{ article.start_time|date:"d/m/Y"  }} au {{ article.end_time|date:"d/m/Y"  }}
                {%else%}
                le {{ article.start_time|date:"d/m/Y"  }}

            {% endif %}
              </a>
          </p>
        {% endif %}
        {%if dates or article.auteur == request.user or article.estPublic %}
        <p>

            <button type="button" class="btn" data-toggle="modal" data-target="#dates">
             Dates {%if article.start_time %}supplémentaires{%endif%}
            </button>
            <!-- Modal -->
            <div class="modal fade" id="dates" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog textcenter" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                      Dates
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                      {%for date in dates %}
                     <p>{{date.start_time |date:"l d F Y"}}</p>
                      {%empty%}
                      -
                      {%endfor%}
                    {%if article.auteur == request.user or article.estPublic %}
                      <p><a class="btn btn-success" href="{% url 'blog:ajouterEvenementArticle' id=article.id %}" >Ajouter une date</a></p>
                    {% endif %}
                  </div>
                </div>
              </div>
            </div>
          </p>
  {% endif %}
    </div>
</div>

<div class="row">
<div class="col">
      <h3 style="text-indent: 30px;"> {{ article.titre }}</h3>
</div>
</div>
<div class="row">
<div class="col">
   {{ article.contenu |safe}}
</div>
</div>
</div>


<hr>

{% include 'commentaires.html' %}

{% endblock %}