blog/urls.py
# -*- coding: utf-8 -*-
"""bourseLibre URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add an import:  from blog__ import urls as blog_urls
    2. Add a URL to urlpatterns:  url(r'^blog__/', include(blog_urls))
"""
from django.conf.urls import url
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'blog'

urlpatterns = [
    url(r'^accueil/$', views.accueil, name="forum"),
    url(r'^articles/$', views.ListeArticles.as_view(), name="index"),
    # url(r'^newPost/', views.ajouterArticle, name='ajouterArticle'),
    # url(r'^article/(?P<slug>.+)$', views.lire, name='lire'),

    url(r'^article/(?P<slug>[-\w]+)$', views.lireArticle, name='lireArticle'),
    url(r'^modifierArticle/(?P<slug>[-\w]+)$', login_required(views.ModifierArticle.as_view(), login_url='/auth/login/'), name='modifierArticle'),
    url(r'^suiveursArticle/(?P<slug>[-\w]+)$', views.articles_suivis, name='suiveursArticle'),
    url(r'^supprimerArticle/(?P<slug>[-\w]+)$', login_required(views.SupprimerArticle.as_view(), login_url='/auth/login/'), name='supprimerArticle'),
    url(r'^ajouterArticle/$', login_required(views.ajouterArticle), name='ajouterNouvelArticle'),

    url(r'^suivre_article/(?P<slug>[-\w]+)/$', views.suivre_article, name='suivre_article'),
    url(r'^suivre_articles/$', views.suivre_articles, name='suivre_articles'),

    url(r'^modifierCommentaireArticle/(?P<id>[0-9]+)$',
        login_required(views.ModifierCommentaireArticle.as_view(), login_url='/auth/login/'),
        name='modifierCommentaireArticle'),
    url(r'ajouterEvenement/$', views.ajouterEvenement, name='ajouterEvenement'),
    url(r'ajouterEvenementArticle/(?P<id>[0-9]+)$', views.ajouterEvenementArticle, name='ajouterEvenementArticle'),

]

cal/urls.py
# cal/urls.py

from django.conf.urls import url
from . import views

app_name = 'cal'
urlpatterns = [
    url(r'', views.agenda, name='agenda'),
]

uppm/urls.py
from django.urls import path
from django.conf.urls import include, url
from uppm import views
from django.views.generic import TemplateView
from .views import handler400 as h400, handler403  as h403, handler404  as h404, handler500  as h500

# On import les vues de Django, avec un nom spécifique
from django.contrib.auth.decorators import login_required

# admin.autodiscover()
from django.contrib import admin

urlpatterns = [
    url(r'^summernote/', include('django_summernote.urls')),
    url(r'^captcha/', include('captcha.urls')),
    path(r'agenda/', include('cal.urls')),
    url(r'^forum/', include('blog.urls', namespace='bourseLibre.blog')),
    url('^', include('django.contrib.auth.urls')),
    url(r'^$', views.bienvenue, name='bienvenue'),
    url(r'^bienvenue/$', views.bienvenue, name='bienvenue'),
    url(r'^faq/$', views.faq, name='faq'),
    url(r'^gallerie/$', views.gallerie, name='gallerie'),
    url(r'^notifications/$', views.notifications, name='notifications'),
    url(r'^notifications/news/$', views.notifications_news, name='notifications_news'),
    url(r'^notificationsParDate/$', views.notificationsParDate, name='notificationsParDate'),
    url(r'^notificationsLues/$', views.notificationsLues, name='notificationsLues'),
    url(r'^dernieresInfos/$', views.dernieresInfos, name='dernieresInfos'),
    url(r'^site/presentation/$', views.presentation_site, name='presentation_site'),
    url(r'^gestion/', admin.site.urls, name='admin',),
    url(r'^merci/$', views.merci, name='merci'),
    url(r'^chercher/produit/$', login_required(views.chercher), name='chercher'),
    url(r'^accounts/profil/(?P<user_id>[0-9]+)/$', login_required(views.profil), name='profil', ),
    url(r'^accounts/profil/(?P<user_username>[-\w.]+)/$', login_required(views.profil_nom), name='profil_nom', ),
    url(r'^accounts/profile/$', login_required(views.profil_courant), name='profil_courant', ),
    url(r'^accounts/profil_inconnu/$', views.profil_inconnu, name='profil_inconnu', ),
    url(r'^accounts/profil_modifier/$', login_required(views.profil_modifier.as_view()), name='profil_modifier', ),
    url(r'^accounts/profil_supprimer/$', login_required(views.profil_supprimer.as_view()), name='profil_supprimer', ),
    url(r'^accounts/profil_contact/(?P<user_id>[0-9]+)/$', login_required(views.profil_contact), name='profil_contact', ),
    url(r'^register/$', views.register, name='senregistrer', ),
    url(r'^password/change/$', views.change_password, name='change_password'),
    path('auth/', include('django.contrib.auth.urls')),

    url(r'^contact_admins/$', views.contact_admins, name='contact_admins', ),
    url(r'^cgu/$', views.cgu, name='cgu', ),
    url(r'^liens/$', views.liens, name='liens', ),
    url(r'^fairedon/$', views.fairedon, name='fairedon', ),
    #url(r'^agenda/$', views.agenda, name='agenda',),
    url(r'^cooperateurs/annuaire/$', login_required(views.annuaire), name='annuaire', ),
    url(r'^cooperateurs/listeFollowers/$', login_required(views.listeFollowers), name='listeFollowers', ),
    url(r'^cooperateurs/carte/$', login_required(views.carte), name='carte', ),

    url(r'^conversations/(?P<destinataire>[-\w.]+)$', login_required(views.lireConversation), name='agora_conversation'),
    url(r'^conversations/(?P<destinataire1>[-\w.]+)/(?P<destinataire2>[-\w.]+)$', login_required(
        views.lireConversation_2noms), name='lireConversation_2noms'),
    url(r'^conversations/$', login_required(views.ListeConversations.as_view()), name='conversations'),
    url(r'^conversations/chercher/$', login_required(views.chercherConversation), name='chercher_conversation'),
    url(r'^suivre_conversation/$', views.suivre_conversations, name='suivre_conversations'),
    url(r'^agora/$', login_required(views.agora), name='agora_general'),
    url(r'^activity/', include('actstream.urls')),
    url(r'^inscription_newsletter/$', views.inscription_newsletter, name='inscription_newsletter', ),
    url(r'^modifierMessage/(?P<id>[0-9]+)(?P<type>[-\w.]+)$', views.modifier_message, name='modifierMessage'),
]


urlpatterns += [
    url(r'^robots\.txt$', TemplateView.as_view(template_name="uppm/robots.txt", content_type='text/plain')),
]

from django.conf import settings
if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = h404
handler500 = h500
handler400 = h400
handler403 = h403

if settings.LOCALL:
    import debug_toolbar
    urlpatterns = [url(r'^__debug__/', include(debug_toolbar.urls)),] + urlpatterns
    #urlpatterns += url('',(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}))

uppm/views.py
# -*- coding: utf-8 -*-
'''
Created on 25 mai 2017

@author: tchenrezi
'''
from django.shortcuts import HttpResponseRedirect, render, redirect#, render, get_object_or_404, redirect, render_to_response,

from .forms import ContactForm, ProfilCreationForm, MessageForm, MessageGeneralForm, \
    ProducteurChangeForm, ChercherConversationForm, InscriptionNewsletterForm, \
    MessageChangeForm
from .models import Profil, Conversation, Message, MessageGeneral, getOrCreateConversation, Suivis, InscriptionNewsletter
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, UpdateView, DeleteView
from django.urls import reverse_lazy, reverse
from django.core.mail import mail_admins, send_mail, BadHeaderError, send_mass_mail

from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.models import Group, User
from django.views.decorators.csrf import csrf_exempt

from django.views.decorators.debug import sensitive_variables
#from django.views.decorators.debug import sensitive_post_parameters

#from django.core.exceptions import ObjectDoesNotExist
from django.db.models import Q, CharField
from django.db.models.functions import Lower
from django.utils.html import strip_tags

from actstream import actions, action
from actstream.models import Action, any_stream, following,followers


from django.utils.timezone import now

CharField.register_lookup(Lower, "lower")

#import sys
#from io import BytesIO
#from django.core.files.uploadedfile import InMemoryUploadedFile
#from PIL import Image
#from braces.views import LoginRequiredMixin

def handler404(request, *args, **kwargs):  #page not found
    response = render(request, "404.html")
    response.status_code = 404
    return response

def handler500(request, *args, **kwargs):   #erreur du serveur
    response = render(request, "500.html")
    response.status_code = 500
    return response

def handler403(request, *args, **kwargs):   #non autorisé
    response = render(request, "403.html")
    response.status_code = 403
    return response

def handler400(request, *args, **kwargs):   #requete invalide
    response = render(request, "400.html")
    response.status_code = 400
    return response

def bienvenue(request):
    nbNotif = 0
    if request.user.is_authenticated:
        nbNotif = getNbNewNotifications(request)

    return render(request, 'bienvenue.html', { "nbNotif": nbNotif })


def presentation_site(request):
    return render(request, 'presentation_site.html')

def gallerie(request):
    return render(request, 'gallerie.html')

def faq(request):
    return render(request, 'faq.html')


def merci(request, template_name='merci.html'):
    return render(request, template_name)


@login_required
def profil_courant(request, ):
    return render(request, 'profil.html', {'user': request.user})


@login_required
def profil(request, user_id):
    try:
        user = Profil.objects.get(id=user_id)
        return render(request, 'profil.html', {'user': user,})
    except User.DoesNotExist:
            return render(request, 'profil_inconnu.html', {'userid': user_id})

@login_required
def profil_nom(request, user_username):
    try:
        user = Profil.objects.get(username=user_username)
        return render(request, 'profil.html', {'user': user, })
    except User.DoesNotExist:
        return render(request, 'profil_inconnu.html', {'userid': user_username})

@login_required
def profil_inconnu(request):
    return render(request, 'profil_inconnu.html')

@login_required
def annuaire(request):
    profils = Profil.objects.filter(accepter_annuaire=True).order_by('username')
    nb_profils = len(Profil.objects.all())
    return render(request, 'annuaire.html', {'profils':profils, "nb_profils":nb_profils} )


@login_required
def listeContacts(request):
    if not request.user.is_membre_collectif:
        return render(request, "notUPPM.html")
    listeMails = [
        {"type":'user_newsletter' ,"profils":Profil.objects.filter(inscrit_newsletter=True), "titre":"Liste des inscrits à la newsletter : "},
         {"type":'anonym_newsletter' ,"profils":InscriptionNewsletter.objects.all(), "titre":"Liste des inscrits anonymes à la newsletter : "},
      {"type":'user_adherent' , "profils":Profil.objects.filter(statut_adhesion=2), "titre":"Liste des adhérents : "},
        {"type":'user_futur_adherent', "profils":Profil.objects.filter(statut_adhesion=0), "titre":"Liste des personnes qui veulent adhérer à UPPM :"}
    ]
    return render(request, 'listeContacts.html', {"listeMails":listeMails})


@login_required
def listeFollowers(request):
    if not request.user.is_membre_collectif:
        return render(request, "notUPPM.html")
    listeArticles = []
    # for art in Projet.objects.all():
    #     suiveurs = followers(art)
    #     if suiveurs:
    #         listeArticles.append({"titre": art.titre, "url": art.get_absolute_url(), "followers": suiveurs, })

    return render(request, 'listeFollowers.html', {"listeArticles":listeArticles})

@login_required
def carte(request):
    profils = Profil.objects.filter(accepter_annuaire=1)
    return render(request, 'carte_cooperateurs.html', {'profils':profils, 'titre': "La carte des coopérateurs*" } )


@login_required
def profil_contact(request, user_id):
    recepteur = Profil.objects.get(id=user_id)
    if request.method == 'POST':
        form = ContactForm(request.POST or None, )
        if form.is_valid():
            sujet = "[permacat] "+ request.user.username + "(" + request.user.email+ ") vous a écrit: "+ form.cleaned_data['sujet']
            message_txt = form.cleaned_data['msg']
            message_html = form.cleaned_data['msg']
            recepteurs = [recepteur.email,]
            if form.cleaned_data['renvoi'] :
                recepteurs = [recepteur.email, request.user.email]

            send_mail(
                sujet,
                message_txt,
                request.user.email,
                recepteurs,
                html_message=message_html,
                fail_silently=False,
                )
            return render(request, 'contact/message_envoye.html', {'sujet': form.cleaned_data['sujet'], 'msg':message_html, 'envoyeur':request.user.username + " (" + request.user.email + ")", "destinataire":recepteur.username + " (" +recepteur.email+ ")"})
    else:
        form = ContactForm()
    return render(request, 'contact/profil_contact.html', {'form': form, 'recepteur':recepteur})


def contact_admins(request):
    if request.method == 'POST':
        form = ContactForm(request.POST or None, )
        if form.is_valid():
            if request.user.is_anonymous :
                envoyeur = "Anonyme "
            else:
                envoyeur = request.user.username + "(" + request.user.email+ ") "

            sujet =  envoyeur + form.cleaned_data['sujet']
            message_txt = envoyeur + ") a envoyé le message suivant : "
            message_html = form.cleaned_data['msg']
            try:
                mail_admins(sujet, message_txt, html_message=message_html)
                if form.cleaned_data['renvoi']:
                    send_mail(sujet, "Vous avez envoyé aux administrateurs du site uppm66.herokuapp.com le message suivant : " + message_html, request.user.email, [request.user.email,], fail_silently=False, html_message=message_html)

                return render(request, 'contact/message_envoye.html', {'sujet': sujet, 'msg': message_html,
                                                       'envoyeur': envoyeur,
                                                       "destinataire": "administrateurs "})
            except BadHeaderError:
                return render(request, 'erreur.html', {'msg':'Invalid header found.'})

            return render(request, 'erreur.html', {'msg':"Désolé, une ereur s'est produite"})
    else:
        form = ContactForm()
    return render(request, 'contact/contact.html', {'form': form, "isContactProducteur":False})

@login_required
class profil_modifier_user(UpdateView):
    model = Profil
    form_class = ProducteurChangeForm
    template_name_suffix = '_modifier'
    fields = ['username', 'first_name', 'last_name', 'email', 'accepter_annuaire', 'inscrit_newsletter']

    def get_object(self):
        return Profil.objects.get(id=self.request.user.id)


class profil_modifier(UpdateView):
    model = Profil
    form_class = ProducteurChangeForm
    template_name_suffix = '_modifier'
    #fields = ['username','email','first_name','last_name', 'site_web','description', 'competences', 'inscrit_newsletter']

    def get_object(self):
        return Profil.objects.get(id=self.request.user.id)

class profil_supprimer(DeleteView):
    model = Profil
    success_url = reverse_lazy('bienvenue')

    def get_object(self):
        return Profil.objects.get(id=self.request.user.id)

@sensitive_variables('password')
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password was successfully updated!')
            return redirect('change_password')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'registration/password_changer_form.html', {
        'form': form
    })

@sensitive_variables('user', 'password1', 'password2')
def register(request):
    if request.user.is_authenticated:
        return render(request, "erreur.html", {"msg":"Vous etes déjà inscrit et authentifié !"})

    form_profil = ProfilCreationForm(request.POST or None)
    if form_profil.is_valid():
        profil_courant = form_profil.save(commit=False,is_active = False)

uppm/templates/notifications/mesSuivis.html
{% extends 'base.html' %}

{% block subtitle %}
<h4>Mes suivis</h4>

{% endblock %}
{% block content %}

<div class="row justify-content-center">
    <div class="col-sm-12 textcenter">
            {% for action in actions %}
        <p>
            {{action}}
        </p>
        {%endfor%}
    </div>
</div>

{% endblock %}

uppm/templates/notifications/notifications.html
{% extends 'base.html' %}
{% load activity_tags %}
{% block subtitle %}
<h4 class = "textcenter "> Notifications par type </h4>


<p class = "textcenter ">
      <a href="{% url 'notifications_news'  %}" class="btn btn-success">
         Notifications récentes
      </a>
</p>
{% endblock %}
{% block content %}
<div class="row justify-content-center"
<div class="card-deck notif justify-content-between">
<div class="card carte-notif notif2  d-md-flex textcenter">
    <div class="card-header textcenter" style="background-color:#f0a868">
      Articles
    </div>
    <ul class="list-group list-group-flush">
  {% for action in articles %}
      {% include "notifications/notifications_template.html" with action=action %}
  {% endfor %}
    </ul>
  </div>
  <div class="card carte-notif notif2  d-md-flex textcenter ">
    <div class="card-header textcenter justify-content-center" style="background-color:#8eaf9d">
      Salon{% if request.user.is_membre_collectif %}s{%endif %}
    </div>
      <div class="card-block"  >
        <ul class="list-group list-group-flush">
          {% for action in salons%}
              {% include "notifications/notifications_template.html" with action=action %}
          {% endfor %}
        </ul>
      </div>
  </div>


  <div class="card carte-notif notif2  d-md-flex textcenter">
    <div class="card-header textcenter" style="background-color:#cacaaa" >
     Mes conversations
    </div>
    <ul class="list-group list-group-flush " >
  {% for action in conversations|slice:":20" %}
      {% include "notifications/notifications_template.html" with action=action %}
  {% endfor %}
    </ul>
  </div>


  <div class="card carte-notif notif2  d-md-flex textcenter">
    <div class="card-header textcenter" style="background-color:#cacaaa" >
     Inscriptions
    </div>
    <ul class="list-group list-group-flush " >
  {% for action in inscriptions|slice:":20" %}
      {% include "notifications/notifications_template.html" with action=action %}
  {% endfor %}
    </ul>
  </div>


<div class="card carte-notif notif2  d-md-flex textcenter">
  <div class="card-header textcenter" style="background-color:#b5ca8d" >
    Mes actions
  </div>
  <ul class="list-group list-group-flush " >
{% activity_stream 'actor' user %}
{% for action in stream|slice:":20" %}
    {% include "notifications/notifications_template.html" with action=action %}
{% endfor %}
  </ul>
</div>
</div>

{% endblock %}

uppm/templates/notifications/notificationsParDate.html
{% extends 'base.html' %}
{% load activity_tags %}
{% block subtitle %}
<h4 class = "textcenter "> Notifications par date

</h4>

<p class = "textcenter ">
      <a href="{% url 'notifications'  %}" class="btn btn-success">
         Toutes les notifications
      </a>
</p>
{% endblock %}
{% block content %}
<div class="row justify-content-center"
<div class="card-deck notif justify-content-between">
<div class="card carte-notif notif3  d-md-flex textcenter">
    <ul class="list-group list-group-flush">
  {% for action in actions %}
      {% include "notifications/notifications_templateParDate.html" with action=action %}
  {% endfor %}
    </ul>
  </div>
</div>

{% endblock %}

uppm/templates/notifications/notifications_last.html
{% extends 'base.html' %}
{% load activity_tags %}
{% block subtitle %}
<h4 class = "textcenter "> Notifications </h4>

<p class = "textcenter ">
      <a href="{% url 'notifications'  %}" class="btn btn-success">
         Toutes les notifications
      </a>
</p>
<hr>
{%if actions%}
<p class = "textcenter "> depuis la dernière fois que vous avez "marqué comme vu" (le {{request.user.date_notifications|date:"d/m/Y"}} à {{request.user.date_notifications|date:"G:i"}})</p>

{% endif %}
{% endblock %}
{% block content %}

{%if actions%}
<p class = "textcenter ">
      <a href="{% url 'notificationsLues'  %}" class="btn btn-primary">
         Marquer comme vu
      </a>
</p>
{% endif %}
<div class="row justify-content-center">
<div class="card-deck notif justify-content-between">
    <div class="card carte-notif-news notif3  d-lg-flex textcenter">
        <ul class="list-group list-group-flush">
	{%if actions%}
      {% for action in actions %}
          {% include "notifications/notifications_template.html" with action=action %}
      {% endfor %}

		{%else%}
            <li class="list-group-item textcenter"  >Pas de nouvelle activité depuis le {{request.user.date_notifications|date:"d/m/Y"}} à {{request.user.date_notifications|date:"G:i"}}</li>
		{%endif%}
            <li class="list-group-item textcenter"  >
                <a href="{% url 'notificationsParDate'  %}" class="btn btn-success btn-sm">Voir toutes les notifications par date</a>
                </li>

        </ul>

    </div>

</div>
</div>

{% endblock %}

uppm/templates/notifications/notifications_news.html
{% extends 'base.html' %}
{% load activity_tags %}
{% block subtitle %}
<h4 class = "textcenter "> Les dernières nouvelles
</h4>

<p class = "textcenter ">
      <a href="{% url 'notifications_news'  %}" class="btn btn-success">
         Activité récente
      </a>
      <a href="{% url 'notifications'  %}" class="btn btn-success">
         Notifications par type
      </a>
      <a href="{% url 'notificationsParDate'  %}" class="btn btn-success">
         Notifications par date
      </a>
</p>
<h6> Voici les projets, articles, fiches, ateliers ainsi que les offres de l'altermarché parus ces 15 derniers jours</h6>
{% endblock %}
{% block content %}


<div class="row justify-content-center">
    <div class="col-sm-12 col-md-6">

    <ul class="list-group list-group-flush">
  {% for info in info_parjour %}
      {% for art in info.infos.0 %}
        {% include "notifications/notifications_template2.html" with action=art color="#f8d7b9"%}
      {%endfor%}
      {% for art in info.infos.1 %}
        {% include "notifications/notifications_template2.html" with action=art  color="#d3ded6"%}
      {%endfor%}
      {% for art in info.infos.2 %}
        {% include "notifications/notifications_template2.html" with action=art color="#d3dcbc" %}
      {%endfor%}
      {% for art in info.infos.3 %}
        {% include "notifications/notifications_template2.html" with action=art color="#d3dcbc" %}
      {%endfor%}
      {% for art in info.infos.4 %}
        {% include "notifications/notifications_template2.html" with action=art color="#d3dcbc" %}
      {%endfor%}
      {% for art in info.infos.5 %}
        {% include "notifications/notifications_template2.html" with action=art color="#d3dcbc" %}
      {%endfor%}

  {% endfor %}
    </ul>
</div>
  </div>
<hr>

{% endblock %}

uppm/templates/notifications/notifications_template.html
{%ifchanged %}<li class="list-group-item textcenter "  style="background-color:#e1e1d0"  >{{action.timestamp|date:"l d F"}}</li>{%endifchanged %}
<li class="list-group-item"  style="{% if request.user.date_notifications > action.timestamp %}background-color:#ffffe6{%endif%}">
    <a href="{%if action.data.url %}{{ action.data.url }}{%endif%} ">({{action.timestamp|date:"G:i"}}) {{action.actor}}
        {%if action.description %}{{action.description}}{% endif %} {%ifequal action.verb 'started following' %} suit la {{action.target}}{% endifequal %}
        </a></li>

uppm/templates/notifications/notifications_template2.html
<li class="list-group-item"  style="background-color:{{color}}">
    <a {%if action.data.url %}href="{{ action.data.url }} "{%endif%}>
         {{action.actor}} {%if action.description %}{{action.description}}{% endif %}
        </a></li>

uppm/templates/notifications/notifications_template3.html
{%ifchanged %}<li class="list-group-item textcenter "  style="background-color:#e1e1d0"  >{{action.timestamp|date:"l d F"}}</li>{%endifchanged %}
<li class="list-group-item"  style="
{% if request.user.date_notifications > action.timestamp %}
background-color:#ffffe6
{%endif%}">
    <a href="{%if action.data.url %}{{ action.data.url }} {%endif%}">({{action.timestamp|date:"G:i"}}) {{action.actor}}
        {%if action.description %}{{action.description}}{% endif %} {%ifequal action.verb 'started following' %} suit la {{action.target}}{% endifequal %}
        </a></li>

uppm/templates/notifications/notifications_templateParDate.html
{%ifchanged %}<li class="list-group-item textcenter "  style="background-color:#e1e1d0"  >{{action.timestamp|date:"l d F"}}</li>{%endifchanged %}
<li class="list-group-item"  style="{% if request.user.date_notifications > action.timestamp %}background-color:#ffffe6{%endif%}">
    <a {%if action.data.url %}href="{{ action.data.url }} "{%endif%}>({{action.timestamp|date:"G:i"}}) {{action.actor}}
        {%if action.description %}{{action.description}}{% endif %} {%ifequal action.verb 'started following' %} suit la {{action.target}}{% endifequal %}
        </a></li>

uppm/templates/notifications/prochaines_rencontres.html
{% extends 'base.html' %}
{% load activity_tags %}
{% block subtitle %}
<h4 class = "textcenter "> Nos prochaines rencontres UPPM
</h4>
{% endblock %}
{% block content %}


<div class="row justify-content-center">
    <div class="col-sm-12 col-md-10 col-lg-8">

    <ul class="list-group list-group-flush  justify-content-center textcenter">
        <li class="list-group-item"><a href="{% url 'blog:lireArticle' visioconference" %}>visioconférence Lundi prochain à partir de 19h</a> </li>
        <li class="list-group-item"><a href="{% url 'blog:lireProjet' lalter-marche-ou-marche-en-monnaies-alternatives %}">Altermarché ; Mercredi 17 juillet </a></li>
        <li class="list-group-item"><a href="{% url 'blog:lireArticle' rencontres-permacat %}">Rencontre mensuelle (1er dimanche du mois) : dimanche 17 juillet. Le lieu encore à définir pour le mois prochain...</li>
    </ul>
    </div>
</div>

<hr>
{% endblock %}